name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: github.repository == 'Finch-API/finch-api-go'

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - run: |
          go build ./...

  
